sudo: required
services:
  - docker

language: node_js
dist: trusty
node_js:
  - "8"
addons:
  chrome: stable
  apt:
    packages:
      - libnss3
      - xvfb
cache:
  directories:
    - node_modules



before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - docker-compose up -d
  
 

